### ISSUE TITLE
Less verbose logs

### ISSUE THREAD

**Issue by hope-portal-services** [tgfischer/serverless-build-client#5]
it would be nice to have a flag like `--verbose` which outputs the ENV logs to the console rather than having this be hard set. ie: `Setting ${variable} to ${environment[variable]}`

might PR it.

**Comment by tgfischer** [comment]
This is a great idea. I'm fairly busy right now with other things though, so I likely won't be able to get to this for a bit. If someone wants to do a pull request for this, that would be awesome :)

Otherwise I'll try to do this when I can

**Comment by tgfischer** [comment]
This is included in release 2.5
