### ISSUE TITLE
Serverless: Failed to compile

### ISSUE THREAD

**Issue by hope-portal-services** [tgfischer/serverless-build-client#7]
This plugin has been working for around 3 months with no issues, it really solved a big problem for our build.

Recently it stopped building and throwing an error that the client failed to compile. I've built the client locally and it works fine, but for some reason now in my CI pipeline, once serverless-build-client is thrown into the mix, it fails.

Wondering if anyone is experiencing similar or has any thoughts on this?

**Comment by tgfischer** [comment]
Do you have any logs?

**Comment by hope-portal-services** [comment]
Yeah, here's what it ends up spitting out.

`Pulling image library/node:latest
Creating image started.
Sending build context to Docker daemon  2.048kB

Step 1/2 : FROM library/node:latest
 ---> 7aef30ae6655
Step 2/2 : RUN npm install -g gulp grunt-cli
 ---> Running in fe3d2658ce83
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/gulp/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules/gulp/node_modules/fsevents/node_modules/abbrev):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/abbrev' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.abbrev.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ansi-regex@2.1.1 (node_modules/gulp/node_modules/fsevents/node_modules/ansi-regex):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/ansi-regex' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.ansi-regex.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: aproba@1.2.0 (node_modules/gulp/node_modules/fsevents/node_modules/aproba):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/aproba' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.aproba.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: balanced-match@1.0.0 (node_modules/gulp/node_modules/fsevents/node_modules/balanced-match):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/balanced-match' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.balanced-match.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: chownr@1.1.3 (node_modules/gulp/node_modules/fsevents/node_modules/chownr):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/chownr' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.chownr.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: code-point-at@1.1.0 (node_modules/gulp/node_modules/fsevents/node_modules/code-point-at):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/code-point-at' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.code-point-at.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: concat-map@0.0.1 (node_modules/gulp/node_modules/fsevents/node_modules/concat-map):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/concat-map' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.concat-map.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: console-control-strings@1.1.0 (node_modules/gulp/node_modules/fsevents/node_modules/console-control-strings):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/console-control-strings' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.console-control-strings.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: core-util-is@1.0.2 (node_modules/gulp/node_modules/fsevents/node_modules/core-util-is):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/core-util-is' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.core-util-is.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: deep-extend@0.6.0 (node_modules/gulp/node_modules/fsevents/node_modules/deep-extend):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/deep-extend' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.deep-extend.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: delegates@1.0.0 (node_modules/gulp/node_modules/fsevents/node_modules/delegates):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/delegates' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.delegates.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: detect-libc@1.0.3 (node_modules/gulp/node_modules/fsevents/node_modules/detect-libc):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/detect-libc' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.detect-libc.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs.realpath@1.0.0 (node_modules/gulp/node_modules/fsevents/node_modules/fs.realpath):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/fs.realpath' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.fs.realpath.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: has-unicode@2.0.1 (node_modules/gulp/node_modules/fsevents/node_modules/has-unicode):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/has-unicode' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.has-unicode.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: inherits@2.0.4 (node_modules/gulp/node_modules/fsevents/node_modules/inherits):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/inherits' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.inherits.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ini@1.3.5 (node_modules/gulp/node_modules/fsevents/node_modules/ini):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/ini' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.ini.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: isarray@1.0.0 (node_modules/gulp/node_modules/fsevents/node_modules/isarray):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/isarray' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.isarray.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@0.0.8 (node_modules/gulp/node_modules/fsevents/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/minimist' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ms@2.1.2 (node_modules/gulp/node_modules/fsevents/node_modules/ms):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/ms' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.ms.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: npm-normalize-package-bin@1.0.1 (node_modules/gulp/node_modules/fsevents/node_modules/npm-normalize-package-bin):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/npm-normalize-package-bin' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.npm-normalize-package-bin.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: number-is-nan@1.0.1 (node_modules/gulp/node_modules/fsevents/node_modules/number-is-nan):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/number-is-nan' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.number-is-nan.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: object-assign@4.1.1 (node_modules/gulp/node_modules/fsevents/node_modules/object-assign):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/object-assign' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.object-assign.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-homedir@1.0.2 (node_modules/gulp/node_modules/fsevents/node_modules/os-homedir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/os-homedir' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.os-homedir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: os-tmpdir@1.0.2 (node_modules/gulp/node_modules/fsevents/node_modules/os-tmpdir):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/os-tmpdir' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.os-tmpdir.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: path-is-absolute@1.0.1 (node_modules/gulp/node_modules/fsevents/node_modules/path-is-absolute):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/path-is-absolute' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.path-is-absolute.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: process-nextick-args@2.0.1 (node_modules/gulp/node_modules/fsevents/node_modules/process-nextick-args):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/process-nextick-args' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.process-nextick-args.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/gulp/node_modules/fsevents/node_modules/rc/node_modules/minimist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/rc/node_modules/minimist' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/rc/node_modules/.minimist.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safe-buffer@5.1.2 (node_modules/gulp/node_modules/fsevents/node_modules/safe-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/safe-buffer' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.safe-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: safer-buffer@2.1.2 (node_modules/gulp/node_modules/fsevents/node_modules/safer-buffer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/safer-buffer' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.safer-buffer.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sax@1.2.4 (node_modules/gulp/node_modules/fsevents/node_modules/sax):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/sax' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.sax.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: semver@5.7.1 (node_modules/gulp/node_modules/fsevents/node_modules/semver):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/semver' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.semver.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: set-blocking@2.0.0 (node_modules/gulp/node_modules/fsevents/node_modules/set-blocking):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/set-blocking' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.set-blocking.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: signal-exit@3.0.2 (node_modules/gulp/node_modules/fsevents/node_modules/signal-exit):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/signal-exit' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.signal-exit.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strip-json-comments@2.0.1 (node_modules/gulp/node_modules/fsevents/node_modules/strip-json-comments):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/strip-json-comments' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.strip-json-comments.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: util-deprecate@1.0.2 (node_modules/gulp/node_modules/fsevents/node_modules/util-deprecate):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/util-deprecate' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.util-deprecate.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: wrappy@1.0.2 (node_modules/gulp/node_modules/fsevents/node_modules/wrappy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/wrappy' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.wrappy.DELETE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yallist@3.1.1 (node_modules/gulp/node_modules/fsevents/node_modules/yallist):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/yallist' -> '/usr/local/lib/node_modules/gulp/node_modules/fsevents/node_modules/.yallist.DELETE'

Executing command: gulp@4.0.2
Executing command: grunt-cli@1.3.2
added 466 packages from 218 contributors in 10.839s
Removing intermediate container fe3d2658ce83
 ---> a7834522af09
Successfully built a7834522af09
Successfully tagged buddy/946320b47ece4d8843486e4892a85c20:1.0
Creating image finished.
Executing command: cd frontend
Executing command: npm install

> core-js@2.6.11 postinstall /buddy/hopeportalservices/frontend/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.4 postinstall /buddy/hopeportalservices/frontend/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> serverless@1.65.0 postinstall /buddy/hopeportalservices/frontend/node_modules/serverless
> node ./scripts/postinstall.js


> styled-components@4.4.1 postinstall /buddy/hopeportalservices/frontend/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/serverless/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/@serverless/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2776 packages from 1909 contributors and audited 939791 packages in 39.252s

54 packages are looking for funding
  run `npm fund` for details

found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Executing command: export AWS_ACCESS_KEY_ID=******ENCRYPTED******
Executing command: AWS_ACCESS_KEY_ID=******ENCRYPTED******
Executing command: export AWS_SECRET_ACCESS_KEY=******ENCRYPTED******
Executing command: AWS_SECRET_ACCESS_KEY=******ENCRYPTED******
Executing command: npx serverless client build
Serverless: Setting the environment variables
Serverless: Setting REACT_APP_STAGE to development
Serverless: Setting REACT_APP_REGION to us-east-1
Serverless: Setting REACT_APP_USER_POOL_ID to us-east-1_r0qr5UoDL
Serverless: Setting REACT_APP_APP_CLIENT_ID to 21v0ba2hdn0un8f7t3v2v773b4
Serverless: Setting REACT_APP_IDENTITY_POOL_ID to us-east-1:739d86b3-ca40-425d-b6f8-d4feda684e96
Serverless: Setting REACT_APP_API_ID to nh6d4r6cs9
Serverless: Setting REACT_APP_APP_NAME to hopetrust.com
Serverless: Setting REACT_APP_API_SERVICE to hopetrust-backend
Serverless: Setting REACT_APP_STRIPE_PUBLIC_KEY to pk_test_OmQvyJhD0F6pd7gXZeraTzxs00PUvqQMUN
Serverless: Building the client
Serverless: > HopeTrust@0.1.0 build-development /buddy/hopeportalservices/frontend
> REACT_APP_STAGE=development react-scripts build
Serverless: Creating an optimized production build...
Serverless: Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.
Serverless: Failed to compile.
Serverless: ./src/Components/MoneyRequests/style.js
  Line 1:18:  'css' is defined but never used    no-unused-vars
  Line 2:10:  'theme' is defined but never used  no-unused-vars

./src/Components/UpcomingServiceRequests/style.js
  Line 1:18:  'css' is defined but never used    no-unused-vars
  Line 2:10:  'theme' is defined but never used  no-unused-vars

./src/Components/UserPermissionsList/style.js
  Line 1:18:  'css' is defined but never used    no-unused-vars
  Line 2:10:  'theme' is defined but never used  no-unused-vars

./src/Components/BudgetWidget/style.js
  Line 1:18:  'css' is defined but never used  no-unused-vars

./src/Components/Modal/Requests/MedicalRequest/index.js
  Line 32:7:  'possible_categories' is assigned a value but never used  no-unused-vars

./src/Components/BudgetWidget/index.js
  Line 3:8:  'PropTypes' is defined but never used  no-unused-vars

./src/Components/GraphContainer/index.js
  Line 50:13:  'getGraphData' is assigned a value but never used  no-unused-vars
  Line 50:27:  'type' is assigned a value but never used          no-unused-vars
Serverless: 
Serverless: npm
Serverless: ERR! code ELIFECYCLE
npm ERR! errno 1
Serverless: npm
Serverless: ERR! HopeTrust@0.1.0 build-development: `REACT_APP_STAGE=development react-scripts build`
npm ERR! Exit status 1
npm
Serverless: ERR! 
npm ERR! Failed at the HopeTrust@0.1.0 build-development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Serverless: 
Serverless: npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-06T16_21_18_179Z-debug.log
 
  Serverless Error ---------------------------------------
 
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2020-03-06T16_21_18_179Z-debug.log
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              13.10.1
     Framework Version:         1.65.0
     Plugin Version:            3.4.1
     SDK Version:               2.3.0
     Components Version:        2.22.3
 
Action failed: see logs above for details`

**Comment by hope-portal-services** [comment]
Working on getting `/root/.npm/_logs/2020-03-06T16_21_18_179Z-debug.log` from the CI provider, it seems I don't have access to more verbose logs out of the box.

**Comment by hope-portal-services** [comment]
Also noting that I can run this full command and build everything locally with no issues. So I suppose the issue is with my CI pipeline. I've matched Node and NPM versions with no luck. Strange.

**Comment by tgfischer** [comment]
My instinct is that this issue is unrelated to `serverless-build-client`. Judging by the error, it looks like Serverless is treating warnings as errors
```
Serverless: Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.
Serverless: Failed to compile.
```
Are those ESLint warnings present when you build your application locally?

**Comment by hope-portal-services** [comment]
They are not present, that was my conclusion also. I'll continue to look into this. At this point I'm sure you're correct and `serverless-build-client` is not at fault here.

**Comment by hope-portal-services** [comment]
FYI, @tgfischer This was NOTHING but some react errors being treated as fatal errors.
